### PR TITLE
Fix build with GHC 9.0.1

### LINKED ISSUE #95: Build failure with GHC 9.0.1
```
src/Foreign/Lua/Core/Error.hs:80:8: error:
    • Couldn't match type: forall a1. Lua.State -> IO a1
                     with: Lua.State -> IO a
      Expected: Lua.ErrorConversion -> Lua.State -> IO a
        Actual: Lua.ErrorConversion -> forall a. Lua.State -> IO a
    • In the first argument of ‘(<$>)’, namely ‘Lua.errorToException’
      In a stmt of a 'do' block:
        f <- Lua.errorToException <$> Lua.errorConversion
      In the expression:
        do f <- Lua.errorToException <$> Lua.errorConversion
           l <- Lua.state
           Lua.liftIO (f l)
    • Relevant bindings include
        throwErrorAsException :: Lua a
          (bound at src/Foreign/Lua/Core/Error.hs:79:1)
   |
80 |   f <- Lua.errorToException <$> Lua.errorConversion
   |        ^^^^^^^^^^^^^^^^^^^^

src/Foreign/Lua/Core/Error.hs:96:41: error:
    • Couldn't match type: forall a1. Lua.State -> IO a1
                     with: Lua.State -> IO a
      Expected: Lua.ErrorConversion -> Lua.State -> IO a
        Actual: Lua.ErrorConversion -> forall a. Lua.State -> IO a
    • In the second argument of ‘(.)’, namely ‘Lua.errorToException’
      In the second argument of ‘(>>=)’, namely
        ‘Lua.liftLua . Lua.errorToException’
      In a stmt of a 'do' block:
        Lua.errorConversion >>= Lua.liftLua . Lua.errorToException
    • Relevant bindings include
        throwMessage :: String -> Lua a
          (bound at src/Foreign/Lua/Core/Error.hs:92:1)
   |
96 |   Lua.errorConversion >>= Lua.liftLua . Lua.errorToException
   |                                         ^^^^^^^^^^^^^^^^^^^^

src/Foreign/Lua/Core/Error.hs:101:12: error:
    • Couldn't match type: forall a1. Lua a1 -> Lua a1 -> Lua a1
                     with: Lua a -> Lua a -> Lua a
      Expected: Lua.ErrorConversion -> Lua a -> Lua a -> Lua a
        Actual: Lua.ErrorConversion -> forall a. Lua a -> Lua a -> Lua a
    • In the first argument of ‘(<$>)’, namely ‘Lua.alternative’
      In a stmt of a 'do' block:
        alt <- Lua.alternative <$> Lua.errorConversion
      In the expression:
        do alt <- Lua.alternative <$> Lua.errorConversion
           x `alt` y
    • Relevant bindings include
        y :: Lua a (bound at src/Foreign/Lua/Core/Error.hs:100:9)
        x :: Lua a (bound at src/Foreign/Lua/Core/Error.hs:100:3)
        (<|>) :: Lua a -> Lua a -> Lua a
          (bound at src/Foreign/Lua/Core/Error.hs:100:5)
    |
101 |     alt <- Lua.alternative <$> Lua.errorConversion
    |            ^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by sjakobi**
Fixes #95.

### CODE REVIEW

**Comment by tarleb** [comment]
Thanks!
