### ISSUE TITLE
Tests do not build on GHC 8.6

### ISSUE THREAD

**Issue by gwils** [hslua/hslua#72]
```
test/Foreign/Lua/CoreTests.hs:228:9: error:
    • No instance for (Control.Monad.Fail.MonadFail Lua)
        arising from a do statement
        with the failable pattern ‘(Just contThread)’
    • In a stmt of a 'do' block: (Just contThread) <- tothread stackTop
      In the second argument of ‘shouldBeResultOf’, namely
        ‘do openlibs
            getglobal "coroutine"
            getfield stackTop "resume"
            pushLuaExpr "coroutine.create(function() coroutine.yield(9) end)"
            ....’
      In the second argument of ‘(=:)’, namely
        ‘Yield
           `shouldBeResultOf`
             do openlibs
                getglobal "coroutine"
                getfield stackTop "resume"
                pushLuaExpr "coroutine.create(function() coroutine.yield(9) end)"
                ....’
    |
228 |         (Just contThread) <- tothread stackTop
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This can be fixed by adding an `instance MonadFail Lua` (which cannot be derived), or by handling the `Maybe` differently in that piece of code.
