### ISSUE TITLE
Compatibility with mtl-2.3

### ISSUE THREAD

**Issue by sjakobi** [hslua/hslua#122]
Changelog: https://github.com/haskell/mtl/blob/046bd051a5bc588c6f22e585eec801d6886a052c/CHANGELOG.markdown#23----2022-05-07

`hslua-objectorientation` will need code changes:

```
src/HsLua/ObjectOrientation.hs:229:3: error:
    Variable not in scope: when :: Bool -> LuaE e () -> LuaE e ()
    |
229 |   when created $ do
    |   ^^^^

src/HsLua/ObjectOrientation.hs:233:5: error:
    Variable not in scope:
      forM_
        :: [(Operation, fn)] -> ((Operation, fn) -> LuaE e ()) -> LuaE e a2
    |
233 |     forM_ (udOperations ty) $ \(op, f) -> do
    |     ^^^^^

src/HsLua/ObjectOrientation.hs:285:3: error:
    Variable not in scope: void :: LuaE e (Map Name ()) -> LuaE e ()
    |
285 |   void $ flip Map.traverseWithKey (udProperties ty) $ \name prop -> do
    |   ^^^^

src/HsLua/ObjectOrientation.hs:294:3: error:
    Variable not in scope: void :: LuaE e2 (Map Name ()) -> LuaE e ()
    |
294 |   void $ flip Map.traverseWithKey (udProperties ty) $ \name prop -> do
    |   ^^^^

src/HsLua/ObjectOrientation.hs:305:3: error:
    Variable not in scope: void :: LuaE e (Map Name ()) -> LuaE e ()
    |
305 |   void $ flip Map.traverseWithKey (udMethods ty) $ \name fn -> do
    |   ^^^^

src/HsLua/ObjectOrientation.hs:313:3: error:
    Variable not in scope:
      void :: LuaE e1 (Map AliasIndex ()) -> LuaE e ()
    |
313 |   void $ flip Map.traverseWithKey (udAliases ty) $ \name propSeq -> do
    |   ^^^^

src/HsLua/ObjectOrientation.hs:370:11: error:
    Variable not in scope: void :: LuaE e0 Bool -> LuaE e a0
    |
370 |           void $ putuserdata @[itemtype] (nthBottom 1) lazyListStateName rest
    |           ^^^^

src/HsLua/ObjectOrientation.hs:375:7: error:
    Variable not in scope:
      forM_
        :: [(Lua.Integer, itemtype)]
           -> ((Lua.Integer, itemtype) -> LuaE e ()) -> LuaE e a1
    |
375 |       forM_ (zip [(curindex + 1)..] as) $ \(i, a) -> do
    |       ^^^^^

src/HsLua/ObjectOrientation.hs:398:7: error:
    Variable not in scope: void :: LuaE e3 Bool -> LuaE e a3
    |
398 |       void (newudmetatable lazyListStateName)
    |       ^^^^

src/HsLua/ObjectOrientation.hs:401:7: error:
    Variable not in scope: void :: LuaE e4 Bool -> LuaE e ()
    |
401 |       void (setiuservalue (nth 2) 1)
    |       ^^^^

src/HsLua/ObjectOrientation.hs:441:66: error:
    • Variable not in scope:
        (<$!>) :: ([itemtype] -> a) -> Peek e [itemtype] -> Peek e a
    • Perhaps you meant ‘<$>’ (imported from Prelude)
    |
441 | setList (_pushspec, (peekItem, updateList)) x = (x `updateList`) <$!> do
    |                                                                  ^^^^

src/HsLua/ObjectOrientation.hs:465:24: error:
    • Variable not in scope:
        (<$!>)
          :: ([itemtype] -> [itemtype])
             -> Peek e [itemtype] -> Peek e [itemtype]
    • Perhaps you meant ‘<$>’ (imported from Prelude)
    |
465 |                   (y:) <$!> itemsAfter (i + 1)
    |                        ^^^^
```

**Comment by tarleb** [comment]
Thanks for the heads-up! I've released hslua-objectorientation-2.2.0.1 to fix this and will do revisions of the other packages to allow mtl-2.3.

**Comment by sjakobi** [comment]
Thanks for the quick response, @tarleb! :)

Unfortunately I'm now seeing a build failure in `hslua-packaging`:

```
Failed to build hslua-packaging-2.2.0.
Build log (
/home/simon/.cabal/logs/ghc-9.2.2/hslua-packaging-2.2.0-c2e9958f7aff164edfe98162c784a5f495cfab230e2a86a19118a12b5e57a73f.log
):
Configuring library for hslua-packaging-2.2.0..
Preprocessing library for hslua-packaging-2.2.0..
Building library for hslua-packaging-2.2.0..
[1 of 8] Compiling HsLua.Packaging.Types
[2 of 8] Compiling HsLua.Packaging.Rendering
[3 of 8] Compiling HsLua.Packaging.Documentation
[4 of 8] Compiling HsLua.Packaging.Function

src/HsLua/Packaging/Function.hs:192:11: error:
    Variable not in scope:
      forM_
        :: FunctionResults e a
           -> (FunctionResult e0 a -> LuaE e0 ()) -> LuaE e a1
    |
192 |           forM_ fnResults $ \(FunctionResult push _) -> push result
    |           ^^^^^

src/HsLua/Packaging/Function.hs:326:13: error:
    • Variable not in scope:
        (<$!>) :: (a0 -> Maybe a0) -> Peek e a -> Peek e (Maybe a)
    • Perhaps you meant ‘<$>’ (imported from Prelude)
    |
326 |       (Just <$!> parameterPeeker p idx)
    |             ^^^^
```

**Comment by tarleb** [comment]
Huh, I had expected the GitHub Actions test-suite to catch that. Seems like caching got in the way though.

Anyhow, hslua-packaging-2.2.0.1 to the rescue. I tested locally with mtl-2.3 and GHC 8.10 as well as 9.2, and it seems to work now.

**Comment by sjakobi** [comment]
Thanks!

> Huh, I had expected the GitHub Actions test-suite to catch that. Seems like caching got in the way though.

More likely IMHO is that `cabal` preferred to build with `mtl-2.2.2` due to the recent deprecation of v2.3: https://github.com/haskell/mtl/issues/117#issuecomment-1132032909. A fixed v2.3.1 will hopefully be out soon.

**Comment by tarleb** [comment]
Aaaah, then that's why. :)
